# Generated by Django 4.2 on 2024-05-19 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0002_task_google_event_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='google_event_id',
            new_name='google_task_id',
        ),
    ]
